apiVersion: apps/v1
kind: Deployment
metadata:
  name: techno-eks-app
  namespace: techno-eks-app
  labels:
    app: techno-eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techno-eks-app
  template:
    metadata:
      labels:
        app: techno-eks-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: 684066883616.dkr.ecr.us-east-1.amazonaws.com/techno-ecr-malang-hida:latest
        ports:
        - name: http
          containerPort: 2000
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux