apiVersion: v1
kind: Service
metadata:
  name: techno-eks-app
  namespace: techno-eks-app
  labels:
    app: techno-eks-app
spec:
  selector:
    app: techno-eks-app
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000